# Generated by Django 3.2.4 on 2021-06-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
