# Generated by Django 3.2.4 on 2021-07-01 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210629_1918'),
        ('customer', '0005_alter_customer_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='book',
        ),
        migrations.AddField(
            model_name='customer',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.books'),
        ),
    ]
