# Generated by Django 3.2.4 on 2021-07-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20210701_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
