# Generated by Django 3.2.4 on 2021-06-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/author/'),
        ),
        migrations.AlterField(
            model_name='books',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='photos/books/'),
        ),
    ]
