# Generated by Django 3.2.4 on 2021-06-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210629_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.ManyToManyField(related_name='genre', to='books.Genre'),
        ),
    ]
