# Generated by Django 3.2.4 on 2021-06-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_books_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='available_books',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='total_books',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
